#TODO: Case insensitive
#TODO: Config classes
General:
  PermissionsEnabled: false
  SpellAnnounceLevel: 1
  SpellRange: 50
  SuperCommand: magna
  #TODO: Not used at the moment
  CastItem: STICK
Reagents:
  Regular: REDSTONE
  Master: LAPIS_LAZULI
  TransmuteCost: 16
  Level1: 1
  Level2: 3
  Level3: 5
Spellbook:
  Enabled: true
  InscriptionCommand: scripto
  WriteReagent: INK_SAC
  Cooldown: 5
